// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// Regenerate the knowledge-base index by scanning all per-video synopsis files.
//
// The synopsis format consumed here (the TL;DR line prefix, the "single
// non-transcript *.md" locator) is defined in
// scripts/playlist-ingest/synopsis-contract.md — its "Machine contract"
// section. Change the format there and the parsing here in the same diff.
//
// Output: $ROOT/youtube-knowledge-base.md — a two-column markdown table sorted
// by upload date, newest first. The first column stacks title (linked to the
// synopsis), channel, and date · duration on three lines; the second carries
// the TL;DR from the synopsis, falling back to the first sentence of the
// Synopsis section for legacy entries.
//
// The filename serves as the page title (no in-doc H1) so GitHub and Obsidian
// render it without a duplicate heading.

// videoMeta is the subset of yt-dlp's metadata the index uses.
type videoMeta struct {
	Title      string  `json:"title"`
	Channel    string  `json:"channel"`
	Uploader   string  `json:"uploader"`
	UploadDate string  `json:"upload_date"`
	Duration   float64 `json:"duration"`
	WebpageURL string  `json:"webpage_url"`

	// durationRaw preserves whether the source value was integral. The shell
	// implementation tested the raw JSON text against ^[0-9]+$ and rendered a
	// dash for anything else, including a fractional duration; keeping that
	// behaviour avoids a cosmetic diff across the whole index on first run.
	durationIsInt bool
}

const missing = "–" // en dash, as the shell implementation emitted

var tldrRe = regexp.MustCompile(`^\*\*TL;DR\*\*:[[:space:]]*`)

var caveatRe = regexp.MustCompile(`^\*\*Caveat\*\*:[[:space:]]*`)

// sentenceEnd trims a fallback line to its first sentence.
var sentenceEnd = regexp.MustCompile(`([.!?]).*`)

func cmdBuildIndex(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("build-index", flag.ContinueOnError)
	fs.SetOutput(stderr)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	root := os.Getenv("YOUTUBE_INGEST_ROOT")
	if root == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(stderr, "ytt: locating home directory: %v\n", err)
			return 1
		}
		root = filepath.Join(home, "think", "knowledge", "youtube")
	}
	index := filepath.Join(root, "youtube-knowledge-base.md")

	rows, err := collectRows(root)
	if err != nil {
		fmt.Fprintf(stderr, "ytt: %v\n", err)
		return 1
	}

	var b strings.Builder
	fmt.Fprintf(&b, "Auto-generated by `ytt build-index`. Last updated %s.\n\n",
		time.Now().Format("2006-01-02T15:04-0700"))
	b.WriteString("| Video | TL;DR |\n")
	b.WriteString("|-------|-------|\n")
	for _, r := range rows {
		b.WriteString(r.row)
		b.WriteByte('\n')
	}
	if len(rows) == 0 {
		// The shell version piped an empty row set through `cut`, which emitted
		// a single blank line. Preserved so an empty tree yields an identical
		// file rather than a one-byte diff.
		b.WriteByte('\n')
	}

	if err := os.WriteFile(index, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(stderr, "ytt: writing index: %v\n", err)
		return 1
	}
	fmt.Fprintf(stderr, "wrote %s (%d entries)\n", index, len(rows))
	return 0
}

type indexRow struct {
	// sortKey is the upload date, or "00000000" when unknown, so undated
	// entries sink to the bottom.
	sortKey string
	row     string
}

func collectRows(root string) ([]indexRow, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading %s: %w", root, err)
	}

	var rows []indexRow
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		id := entry.Name()
		dir := filepath.Join(root, id)
		synopsis, slug := findSynopsis(dir)
		if synopsis == "" {
			continue
		}

		meta := readMeta(filepath.Join(dir, "meta.json"), id)
		tldr, caveat := extractTLDR(synopsis)

		url := meta.WebpageURL
		if url == "" {
			url = "https://www.youtube.com/watch?v=" + id
		}
		cell := escapePipes(tldr)
		if caveat != "" {
			cell += formatIndexCaveat(caveat)
		}
		row := fmt.Sprintf("| **[%s](%s/%s)** ([yt](%s))<br>%s<br>%s · %s | %s |",
			escapePipes(meta.Title), id, slug, url,
			escapePipes(channelOf(meta)),
			formatDate(meta.UploadDate), formatDuration(meta),
			cell)

		key := meta.UploadDate
		if key == "" {
			key = "00000000"
		}
		rows = append(rows, indexRow{sortKey: key, row: row})
	}

	// The shell implementation sorted the tab-joined "key\trow" lines with
	// `sort -r`, i.e. reverse lexicographic over the whole line. Replicated
	// exactly, so ties break identically rather than by directory order.
	sort.Slice(rows, func(i, j int) bool {
		a := rows[i].sortKey + "\t" + rows[i].row
		b := rows[j].sortKey + "\t" + rows[j].row
		return a > b
	})
	return rows, nil
}

// findSynopsis returns the synopsis path and its basename: the single *.md in
// dir that is not a transcript, and is non-empty.
//
// Entries are considered in sorted order. The shell version used `find
// -print -quit`, which took whatever the filesystem offered first; sorting
// makes the choice deterministic when a directory somehow holds two.
func findSynopsis(dir string) (path, slug string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", ""
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".md") || strings.HasPrefix(name, "transcript") {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		full := filepath.Join(dir, name)
		if st, err := os.Stat(full); err == nil && st.Size() > 0 {
			return full, name
		}
	}
	return "", ""
}

func readMeta(path, id string) videoMeta {
	// A missing meta.json is normal for a hand-added entry; fall back to the
	// video id rather than skipping the row.
	m := videoMeta{Title: id}
	data, err := os.ReadFile(path)
	if err != nil {
		return m
	}
	// Decode twice: once into the struct, once loosely so the raw duration
	// token can be checked for integrality.
	if err := json.Unmarshal(data, &m); err != nil {
		return videoMeta{Title: id}
	}
	if m.Title == "" {
		m.Title = "(unknown)"
	}
	var loose map[string]json.RawMessage
	if err := json.Unmarshal(data, &loose); err == nil {
		if raw, ok := loose["duration"]; ok {
			tok := strings.TrimSpace(string(raw))
			m.durationIsInt = tok != "" && !strings.ContainsAny(tok, ".eE") && tok[0] != '-'
		}
	}
	return m
}

// channelOf mirrors jq's `.channel // .uploader // "–"`.
func channelOf(m videoMeta) string {
	if m.Channel != "" {
		return m.Channel
	}
	if m.Uploader != "" {
		return m.Uploader
	}
	return missing
}

func formatDuration(m videoMeta) string {
	secs := int(m.Duration)
	if !m.durationIsInt || secs <= 0 {
		return missing
	}
	return fmt.Sprintf("%d:%02d", secs/60, secs%60)
}

func formatDate(d string) string {
	if len(d) != 8 {
		return missing
	}
	for _, r := range d {
		if r < '0' || r > '9' {
			return missing
		}
	}
	return d[0:4] + "-" + d[4:6] + "-" + d[6:8]
}

// escapePipes keeps a cell from breaking the markdown table.
func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}

// formatIndexCaveat renders a Caveat remainder under the TL;DR. New
// synopses start the remainder with ⚠️ and/or 👎; those are kept as
// written. A legacy unmarked line (Caveat-iff-Critique era) is prefixed
// 👎 so existing entries do not change meaning.
func formatIndexCaveat(caveat string) string {
	s := strings.TrimSpace(caveat)
	if s == "" {
		return ""
	}
	if strings.HasPrefix(s, "⚠") || strings.HasPrefix(s, "👎") {
		return "<br>" + escapePipes(s)
	}
	return "<br>👎 " + escapePipes(s)
}

// extractTLDR pulls the summary out of a synopsis: the first **TL;DR**: line,
// else the first non-empty line of the Synopsis section trimmed to one
// sentence (legacy entries predate the TL;DR convention). It also returns the
// first **Caveat**: line, or "" when the synopsis has none.
func extractTLDR(path string) (tldr, caveat string) {
	f, err := os.Open(path)
	if err != nil {
		return "", ""
	}
	defer f.Close()

	var fallback string
	inSynopsis := false
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if tldr == "" && tldrRe.MatchString(line) {
			// The first TL;DR wins outright over any fallback.
			tldr = tldrRe.ReplaceAllString(line, "")
			continue
		}
		if caveat == "" && caveatRe.MatchString(line) {
			caveat = caveatRe.ReplaceAllString(line, "")
			continue
		}
		if tldr != "" && caveat != "" {
			return tldr, caveat
		}
		if fallback != "" {
			continue // keep scanning for TL;DR/Caveat; the fallback is settled
		}
		switch {
		case strings.HasPrefix(line, "## Synopsis"):
			inSynopsis = true
		case inSynopsis && strings.HasPrefix(line, "## "):
			inSynopsis = false
		case inSynopsis && strings.TrimSpace(line) != "":
			fallback = sentenceEnd.ReplaceAllString(line, "$1")
		}
	}
	if tldr == "" {
		tldr = fallback
	}
	return tldr, caveat
}
