#!/usr/bin/env python3
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0
"""Generate the Homebrew formula for ytt at a given release tag.

Run during the release workflow (on release:published) to emit a fresh
formula whose source sha256 and Python resource pins match the release's
actual artefacts. The rendered formula goes to stdout; the workflow pushes
it to marcelocantos/homebrew-tap.

Usage:
  brew-formula-gen.py <tag>

The tag must already exist as a GitHub release on marcelocantos/ytt so the
source tarball URL resolves. The script resolves the project's Python deps
by installing the release tarball into a scratch venv, then queries PyPI
for each dep's current sdist URL and sha256.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = "marcelocantos/ytt"
PROJECT = "ytt"
DESC = "Fetch YouTube video transcripts from the command-line"
PYTHON = "python@3.13"
SKIP = {"pip", "setuptools", "wheel", PROJECT}


def fetch_sdist(name: str, version: str) -> tuple[str, str]:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    data = json.loads(urllib.request.urlopen(url).read())
    for f in data["urls"]:
        if f["packagetype"] == "sdist":
            return f["url"], f["digests"]["sha256"]
    raise SystemExit(f"brew-formula-gen: no sdist for {name} {version}")


def resolve_deps(tarball_url: str) -> list[tuple[str, str]]:
    with tempfile.TemporaryDirectory() as td:
        venv = Path(td) / "venv"
        subprocess.run(
            [sys.executable, "-m", "venv", str(venv)], check=True,
        )
        pip = venv / "bin" / "pip"
        py = venv / "bin" / "python"
        subprocess.run(
            [str(pip), "install", "--quiet", tarball_url],
            check=True,
        )
        listing = subprocess.run(
            [str(py), "-c",
             "from importlib.metadata import distributions\n"
             "for d in distributions():\n"
             "    print(d.metadata['Name'], d.version, sep='\\t')"],
            check=True, capture_output=True, text=True,
        ).stdout
    deps: list[tuple[str, str]] = []
    for line in listing.splitlines():
        name, version = line.split("\t")
        if name.lower() in {s.lower() for s in SKIP}:
            continue
        deps.append((name, version))
    deps.sort(key=lambda d: d[0].lower())
    return deps


def render_formula(tag: str) -> str:
    tarball_url = f"https://github.com/{REPO}/archive/refs/tags/{tag}.tar.gz"
    tarball_sha = hashlib.sha256(urllib.request.urlopen(tarball_url).read()).hexdigest()
    deps = resolve_deps(tarball_url)
    class_name = "".join(p.capitalize() for p in PROJECT.split("-"))

    resource_blocks = "\n".join(
        f'  resource "{name}" do\n'
        f'    url "{url}"\n'
        f'    sha256 "{sha}"\n'
        f'  end\n'
        for name, ver in deps
        for (url, sha) in [fetch_sdist(name, ver)]
    )

    return f'''# typed: true
# frozen_string_literal: true

# This file is regenerated by scripts/brew-formula-gen.py on each release.
# Do not edit by hand — changes will be overwritten.
class {class_name} < Formula
  include Language::Python::Virtualenv

  desc "{DESC}"
  homepage "https://github.com/{REPO}"
  url "{tarball_url}"
  sha256 "{tarball_sha}"
  license "Apache-2.0"

  depends_on "{PYTHON}"

{resource_blocks}
  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "{PROJECT} #{{version}}", shell_output("#{{bin}}/{PROJECT} --version")
    assert_match "Exit codes", shell_output("#{{bin}}/{PROJECT} --help-agent")
    # No-arg invocation should exit 2 (usage error).
    shell_output("#{{bin}}/{PROJECT} 2>&1", 2)
  end
end
'''


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"usage: {argv[0]} <tag>", file=sys.stderr)
        return 2
    print(render_formula(argv[1]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
