#!/usr/bin/env bash
# Regenerate the knowledge-base index by scanning all per-video synopsis files.
#
# Output: $ROOT/youtube-knowledge-base.md — a two-column markdown table sorted
# by upload date (newest first). The first column packs title (linked to the
# synopsis), channel, date, and duration onto two lines; the second column
# carries the TL;DR line from the synopsis. Falls back to the first sentence
# of the Synopsis section if no TL;DR line exists (legacy entries).
#
# The filename serves as the page title (no in-doc H1) so GitHub and Obsidian
# render it cleanly without a duplicate heading.

set -euo pipefail

ROOT="${YOUTUBE_INGEST_ROOT:-$HOME/think/knowledge/youtube}"
INDEX="$ROOT/youtube-knowledge-base.md"

extract_tldr() {
    local syn="$1"
    local line
    line=$(grep -m1 -E '^\*\*TL;DR\*\*:' "$syn" 2>/dev/null \
        | sed -E 's/^\*\*TL;DR\*\*:[[:space:]]*//')
    if [[ -n "$line" ]]; then
        printf '%s' "$line"
        return
    fi
    # Fallback: first non-empty line after "## Synopsis", trimmed to one sentence.
    awk '
        /^## Synopsis/ { in_syn=1; next }
        in_syn && /^## / { exit }
        in_syn && NF { print; exit }
    ' "$syn" | sed -E 's/([.!?]).*/\1/'
}

format_duration() {
    local secs="${1:-0}"
    if [[ "$secs" =~ ^[0-9]+$ ]] && (( secs > 0 )); then
        printf '%d:%02d' $((secs / 60)) $((secs % 60))
    else
        printf '–'
    fi
}

format_date() {
    local d="${1:-}"
    if [[ "$d" =~ ^[0-9]{8}$ ]]; then
        printf '%s-%s-%s' "${d:0:4}" "${d:4:2}" "${d:6:2}"
    else
        printf '–'
    fi
}

# Collect rows: tab-separated (sort key, formatted row).
ROWS=$(
    for dir in "$ROOT"/*/; do
        # The synopsis is the (single) *.md file in $dir that isn't a
        # transcript. Filenames are topic-based slugs chosen at ingest.
        synopsis=$(find "$dir" -maxdepth 1 -type f -name '*.md' \
            ! -name 'transcript*' -print -quit)
        [[ -n "$synopsis" && -s "$synopsis" ]] || continue
        id="$(basename "$dir")"
        slug_file="$(basename "$synopsis")"
        meta="$dir/meta.json"
        if [[ -f "$meta" ]]; then
            title=$(jq -r '.title    // "(unknown)"' "$meta")
            channel=$(jq -r '.channel // .uploader // "–"' "$meta")
            updated=$(jq -r '.upload_date // ""' "$meta")
            dur=$(jq -r '.duration    // 0'  "$meta")
            url=$(jq -r '.webpage_url // ""' "$meta")
        else
            title="$id"; channel="–"; updated=""; dur=0; url=""
        fi
        tldr=$(extract_tldr "$synopsis")
        # Escape pipes so they don't break the markdown table.
        title_esc=${title//|/\\|}
        channel_esc=${channel//|/\\|}
        tldr_esc=${tldr//|/\\|}
        date_str=$(format_date "$updated")
        dur_str=$(format_duration "$dur")
        link_url=${url:-https://www.youtube.com/watch?v=$id}
        row=$(printf '| **[%s](%s/%s)** ([yt](%s))<br>%s · %s · %s | %s |' \
            "$title_esc" "$id" "$slug_file" "$link_url" \
            "$channel_esc" "$date_str" "$dur_str" "$tldr_esc")
        # Sort key: upload_date if present (YYYYMMDD sorts naturally), else "00000000".
        printf '%s\t%s\n' "${updated:-00000000}" "$row"
    done | sort -r
)

{
    printf 'Auto-generated by `youtube-ingest/build-index.sh`. '
    printf 'Last updated %s.\n\n' "$(date +%Y-%m-%dT%H:%M%z)"
    printf '| Video | TL;DR |\n'
    printf '|-------|-------|\n'
    printf '%s\n' "$ROWS" | cut -f2-
} > "$INDEX"

count=$(printf '%s\n' "$ROWS" | grep -c . || true)
printf 'wrote %s (%d entries)\n' "$INDEX" "$count" >&2
